/* RETRIEVE ALL CUSTOMERS FROM GERMANY */
SELECT * FROM customers
WHERE country = 'Germany';

/* RETRIEVE ALL CUSTOMERS WHO ARE NOT FROM GERMANY */
SELECT * FROM customers
WHERE country <> 'Germany';

SELECT * FROM customers
WHERE country != 'Germany';

/* RETRIEVE ALL CUSTOMERS WITH A SCORE GREATER THAN 500 */
SELECT * FROM customers
WHERE score > 500;

/* RETRIEVE ALL CUSTOMERS WITH A SCORE OF 500 OR MORE */
SELECT * FROM customers
WHERE score >= 500;

/* RETRIEVE ALL CUSTOMERS WITH A SCORE LESS THAN 500 */
SELECT * FROM customers
WHERE score < 500;

/* RETRIEVE ALL CUSTOMERS WITH A SCORE OF 500 OR LESS */
SELECT * FROM customers
WHERE score <= 500;

/* RETRIEVE ALL CUSTOMERS WHO ARE FROM USA AND HAVE A SCORE
GREATER THAN 500 */
SELECT * FROM customers
WHERE country = 'USA'
AND score > 500;

/* RETRIEVE ALL CUSTOMERS WHO ARE EITHER FROM THE USA OR
HAVE A SCORE GREATER THAN 500 */
SELECT * FROM customers
WHERE country = 'USA'
OR score > 500;

/* RETRIEVE ALL CUSTOMERS WITH A SCORE NOT LESS THAN 500 */
SELECT * FROM customers
WHERE NOT score < 500; 

/* RETRIEVE ALL CUSTOMERS WHOSE SCORE FALLS IN THE RANGE
BETWEEN 100 AND 500 */
SELECT * 
FROM customers
WHERE score BETWEEN 100 AND 500;

SELECT * 
FROM customers
WHERE score >= 100 AND score <= 500;

/* RETRIEVE ALL CUSTOMERS FROM EITHER GERMANY OR USA */
SELECT *
FROM customers
WHERE country = 'Germany' OR country = 'USA';

SELECT *
FROM customers
WHERE country IN ('Germany', 'USA');

/* FIND ALL CUSTOMERS WHOSE FIRST NAME STARTS WITH M */
SELECT *
FROM customers
WHERE first_name LIKE 'M%';

/* FIND ALL CUSTOMERS WHOSE FIRST NAME ENDS WITH N */
SELECT *
FROM customers
WHERE first_name LIKE '%n';

/* FIND ALL CUSTOMERS WHOSE FIRST NAME CONTAINS R */
SELECT *
FROM customers
WHERE first_name LIKE '%r%';

/* FIND ALL CUSTOMERS WHOSE FIRST NAME HAS R IN THE
THIRD POSITION */
SELECT *
FROM customers
WHERE first_name LIKE '__r%'