-- THIS IS A COMMENT --

-- RETRIEVE ALL CUSTOMER DATA --
SELECT * FROM customers;

-- RETRIEVE ALL ORDER DATA --
SELECT * FROM orders;

-- RETRIEVE CUSTOMER NAME, COUNTRY AND SCORE --
SELECT first_name, 
	   country, 
	   score 
FROM customers;

-- RETRIEVE CUSTOMER DATA WHERE SCORE != 0 --
SELECT *
FROM customers
WHERE score != 0;

-- RETRIEVE CUSTOMERS FROM GERMANY --
SELECT *
FROM customers
WHERE country = 'Germany';

-- RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE HIGHEST SCORE FIRST --
SELECT * 
FROM customers
ORDER BY score DESC;

-- RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE LOWEST SCORE FIRST --
SELECT * 
FROM customers
ORDER BY score ASC;

-- RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE COUNTRY AND THEN BY THE HIGHEST SCORE --
SELECT * FROM customers
ORDER BY country ASC, score DESC;

-- FIND THE TOTAL SCORE FOR EACH COUNTRY --
SELECT country, SUM(score) AS total_scores
FROM customers
GROUP BY country;

/* FIND THE AVERAGE SCORE FOR EACH COUNTRY
CONSIDERING ONLY CUSTOMERS WITH A SCORE NOT EQUAL TO 0
AND RETURN ONLY THOSE COUNTRIES WITH 
AN AVERAGE SCORE GREATER THAN 430 */

SELECT country, AVG(score) AS average_score
FROM customers
WHERE score != 0
GROUP BY country
HAVING AVG(score) > 430;

-- RETURN UNIQUE LIST OF ALL COUNTRIES --
SELECT DISTINCT country 
FROM customers; 

-- RETRIEVE ONLY 3 CUSTOMERS --
SELECT *
FROM customers
LIMIT 3;

-- RETRIEVE THE TOP 3 CUSTOMERS WITH THE HIGHEST SCORES --
SELECT * 
FROM customers
ORDER BY score DESC
LIMIT 3;

-- RETRIEVE THE LOWEST 2 CUSTOMERS BASED ON THE SCORE --
SELECT * 
FROM customers
ORDER BY score ASC
LIMIT 2;

-- GET THE TWO MOST RECENT ORDERS --
SELECT * 
FROM orders
ORDER BY order_date DESC
LIMIT 2;